#!/bin/bash
# e2e modeling
# all
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e43_all_TFTF_BAR.log &&  echo done 
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e43_all_TFFF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TTTT_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=False use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TTFT_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e43_all_FFTF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_FFFF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_FTTT_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=True use_true_db_pointer=False use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_FTFT_BAR.log && echo done

# prev
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TFTF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TFFF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TTTT_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=False use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TTFT_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_FFTF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_FFFF_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_FTTT_BAR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=False use_true_prev_aspn=True use_true_db_pointer=False use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_FTFT_BAR.log && echo done

# AR
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TTTT_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TFTF_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TTTF_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TFTT_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TTTT_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TFTF_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TTTF_AR.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TFTT_AR.log && echo done

# R
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=True use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TTTT_R.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=True use_all_previous_context=True cuda_device=0 > logs_test_new/e43_all_TTTF_R.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=True use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TTTT_R.log && echo done
nohup python train.py -mode test -cfg eval_load_path=experiments/all_0729_sd11_lr0.0001_bs2_ga16/epoch43_trloss0.56_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=True use_all_previous_context=False cuda_device=0 > logs_test_new/e43_pv_TTTF_R.log && echo done


# URURU
# e2e
nohup python train.py -mode test -cfg context_scheme=URURU eval_load_path=experiments/all_0803_URURU_sd11_lr0.001_bs4_ga16/epoch16_trloss0.44_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=True use_true_db_pointer=True use_true_prev_resp=True use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e16_URURU_BAR.log && echo done
nohup python train.py -mode test -cfg context_scheme=URURU eval_load_path=experiments/all_0803_URURU_sd11_lr0.001_bs4_ga16/epoch16_trloss0.44_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=False use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e16_URURU_genR_BAR.log && echo done
# AR
nohup python train.py -mode test -cfg context_scheme=URURU eval_load_path=experiments/all_0803_URURU_sd11_lr0.001_bs4_ga16/epoch16_trloss0.44_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e16_URURU_AR.log && echo done
nohup python train.py -mode test -cfg context_scheme=URURU eval_load_path=experiments/all_0803_URURU_sd11_lr0.001_bs4_ga16/epoch16_trloss0.44_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=False use_all_previous_context=True cuda_device=0 >  logs_test_new/e16_URURU_genR_AR.log && echo done
# R
nohup python train.py -mode test -cfg context_scheme=URURU eval_load_path=experiments/all_0803_URURU_sd11_lr0.001_bs4_ga16/epoch16_trloss0.44_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=True use_true_curr_bspn=True use_true_curr_aspn=True use_all_previous_context=True cuda_device=0 >  logs_test_new/e16_URURU_R.log && echo done
nohup python train.py -mode test -cfg context_scheme=URURU eval_load_path=experiments/all_0803_URURU_sd11_lr0.001_bs4_ga16/epoch16_trloss0.44_gpt2/ use_true_prev_bspn=True use_true_prev_aspn=False use_true_db_pointer=False use_true_prev_resp=False use_true_curr_bspn=True use_true_curr_aspn=True use_all_previous_context=True cuda_device=0 >  logs_test_new/e16_URURU_genR_R.log && echo done